### ISSUE TITLE
Validators to implement

### ISSUE THREAD

**Issue by harunurhan** [inveniosoftware-contrib/ng2-json-editor#1]
@jmartinm commented on [Tue Sep 06 2016](https://github.com/inspirehep/record-editor/issues/78)

Here we can keep track of all the complex validators (dependent on INSPIRE data model) that can be implemented and that should issue either warnings or errors.

The validation might be implemented on the Python side and the editor will just call the URL to get the validation warnings.
# Errors
# Warnings
- [ ] In the `publication_information` field, 2 cnums are possible in rare situations. Having 2 cnums should trigger a warning.

**Comment by jmartinm** [comment]
Issue moved to [inveniosoftware-contrib/invenio-record-editor #8](https://github.com/inveniosoftware-contrib/invenio-record-editor/issues/8) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jmartinm** [comment]
Issue moved to [inveniosoftware-contrib/invenio-record-editor #9](https://github.com/inveniosoftware-contrib/invenio-record-editor/issues/9) via [**ZenHub**](https://www.zenhub.com/)
