### ISSUE TITLE
Investigate angular2 change detection and re-rendering

### ISSUE THREAD

**Issue by harunurhan** [inveniosoftware-contrib/ng2-json-editor#10]
@harunurhan commented on [Thu Aug 11 2016](https://github.com/inspirehep/record-editor/issues/56)

While working on something else, I realised that angular might be re-rendering some components whose model not changed.

So we should investigate this and optimize the code in order to minimize the UI update to the single component so that we don't  performance issues for big records.
---

@harunurhan commented on [Mon Sep 05 2016](https://github.com/inspirehep/record-editor/issues/56#issuecomment-244699673)

It is probably a good idea to consider using `Immutables` and `Observables` to avoid checking components that aren't changed.

[This article](https://vsavkin.com/change-detection-in-angular-2-4f216b855d4c#.fh4ipmjco) has the basic info how to do that and explains how it improves the performance.

**Comment by harunurhan** [comment]
When `ngOnChanges` calls are logged for components, strangely it is called for top level `TableListFieldComponent` and `ObjectFieldComponent` components when anything is changed. However it is only called once for the initialisation of `ComplexListFieldComponent`, even if when it is directly changed.

**Comment by jmartinm** [comment]
At the moment, the UI events are a bit slow when typing inside of a field, hovering on top of them and so on.

One thing to check is if the problem comes from our HTML markup (too many input elements for example) which is slowing down the browser.

**Comment by harunurhan** [comment]
We can try [this](https://angular.io/docs/ts/latest/guide/user-input.html#!#on-blur) for the typing performance.

**Comment by harunurhan** [comment]
I tested how `immutable.js` improves performance, unfortunately it wasn't much. I might be missing something important I don't know.

However I haven't tried coverting all pipes to `pure` pipes which are only called when reference changed not every time. This might improve the performance more. Before trying I will disable some heavy pipes like the one that does sorting in order to see how it affects performance.

**Comment by harunurhan** [comment]
Went back to immutable approach, and realized that it actually improved performance but the Augry (the chrome dev pluging for debugging angular2 apps) was affecting the performance as well so that's why I wasn't able to see it.

**Comment by paramsingh88** [comment]
I have the same issue with immutablejs. Printing out log in ngOnChanges of a component having inputs bound with @select immutables. It prints out a lot of times even when the app is idle.
<img width="755" alt="screen shot 2017-01-16 at 10 36 48 pm" src="https://cloud.githubusercontent.com/assets/19772006/21992456/870b2cea-dc3c-11e6-989a-f3cdf6c79aeb.png">

**Comment by zzacharo** [comment]
@paramsingh88 Do you use in your component the `changeDetection: ChangeDetectionStrategy.OnPush`. Using only immutable.js will not improve performance. Also ngOnChanges is called anyhow a lot of times even if you hover on a component so having a 'heavy' computational task there is not a good idea.

**Comment by paramsingh88** [comment]
@zzacharo I am using ChangeDetectionStrategy.OnPush already and yeah I noticed this thing lately that on hover over a checkbox row, it triggers change twice but why?? Do you know the reason for this?

**Comment by zzacharo** [comment]
@paramsingh88 When you log the SimpleChange object you see that is referenced twice to the same component?

**Comment by harunurhan** [comment]
@paramsingh88 Angular2 triggers change detection and for every component when there is an event, XHR or `setTimeout`/`setInterval`. And Angular2 skips components without any change in itself and its children components. However  hooks like `ngOnChanges` and `ngDoCheck` are called every change detection no matter what. So doing some stuff in those hooks always slows the app down. You should always try to avoid them. If you must use them, check manually if the properties are actually changed before executing stuff.

**Comment by zzacharo** [comment]
In addition of what @harunurhan said @paramsingh88 In this article http://blog.angular-university.io/how-does-angular-2-change-detection-really-work/ you can see that `The Angular 2 default change detection mechanism is actually quite similar to Angular 1: it compares the values of templates expressions before and after a browser event to see if something changed`. So hovering or even mouse moving will trigger the change detection and therefore `ngOnChanges`.
