### ISSUE TITLE
Move part of field content to a different field 

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#104]
Specially for the case of `misc` field inside of references (but could be useful for the other ones in the future) 

Allow a special character inside of the text area that will enable a UI similar to social media tagging. That means that once the character is inputted, an autocomplete dropdown will appear allowing to select one of the other keys inside of an object. 

When the field is saved, the content after the special character will be moved to the field selected previously in the dropdown.

**Comment by jmartinm** [comment]
Required for reference correction.

**Comment by zzacharo** [comment]
@jmartinm Is this something i can do next or is there something else more important?

**Comment by jmartinm** [comment]
These:

https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/113
https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/79
https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/40

Seem more important to me. So you can take one of them.

**Comment by zzacharo** [comment]
Ok I can check them in order you posted.

**Comment by harunurhan** [comment]
After a quick discussion, it's decided that we'll implement this as in current BibEdit, when you type `$$<shorthand_key>` will move it to `<path_in_json>`. 

And the map of `{<shorthand_key>: <path_in_json>}` will be in configuration.

@jmartinm

**Comment by harunurhan** [comment]
After another discussion, @jmartinm  and I decided that we want to support hooks which is a configuration that allows user applications like record-editor to run functions at certain times such as commiting the value change to the `JsonStoreService`.

This will allows us to put this feature's logic into record-editor, since it's already quite custom thing only we need.
