### ISSUE TITLE
Investigate collection.js integration

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware-contrib/ng2-json-editor#109]
Resolve `Cannot resolve module...` error when trying to install [collection.js]( http://www.collectionsjs.com) in the project.

**Comment by jmartinm** [comment]
Once we merge the shortcuts, you can document here what can be improved from that PR by adding, for example the `SortedMap`

**Comment by jmartinm** [comment]
Duplicate of https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/131
