### ISSUE TITLE
Additional schema-specific configuration support

### ISSUE THREAD

**Issue by harunurhan** [inveniosoftware-contrib/ng2-json-editor#11]
@kaplun commented on [Fri Aug 19 2016](https://github.com/inspirehep/record-editor/issues/63)

Currently #62 and other branches have introduced special `x-editor-*` properties that are expected to be stored in the corresponding JSONSchema.

As discussed IRL, this is not ideal because it mixes the data model with UI specificities. A proposed solution is to have the editor to load a second JSON that is going to be merged with the current schema, so that these additional properties can still refer to specific fields without impacting the original schema.

cc: @jacquerie

**Comment by jmartinm** [comment]
The config can be in a file `config.json` inside of https://github.com/inspirehep/record-editor

The `config` will be an `@Input` for this library.

**Comment by jmartinm** [comment]
Done.
