### ISSUE TITLE
Use collections.js sortedMap for tabindex management

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#131]
In order to simplify the way the `tabindex` is stored (currently with an array and a Map to access path->tabindex), we can make use of collections.js SortedArrayMap (http://www.collectionsjs.com/sorted-array-map)

At the moment, collections.js packaging is not good for integration with `angular-cli`. A first attempt is here (https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/118) but required modification of `example` app.

We can recheck in a while if either packaging of `collectionsjs` or `angular-cli` have improved and can be used.

**Comment by harunurhan** [comment]
not needed anymore.
