### ISSUE TITLE
ERROR in JsonEditorModule is not an NgModule

### ISSUE THREAD

**Issue by cloverzero** [inveniosoftware-contrib/ng2-json-editor#132]
output `ERROR in JsonEditorModule is not an NgModule` when running `ng serve`
using angular-cli:1.0.0-beta.24。
dependencies:
```javascript
"dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/material": "^2.0.0-beta.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "core-js": "^2.4.1",
    "ng2-json-editor": "0.0.9",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  }
```

**Comment by harunurhan** [comment]
Although it is not supposed to, but minor/patch version changes might break the code that works perfectly with an older version. I will try to look into that issue later and upgrade to the latest but meantime you can try it with the dependencies in this repo [record-editor](https://github.com/inspirehep/record-editor/)

**Comment by jmartinm** [comment]
related to https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/69

**Comment by harunurhan** [comment]
Reason: https://github.com/angular/angular-cli/issues/3426

**Comment by harunurhan** [comment]
Should be fixed.
