### ISSUE TITLE
Allow merging of 2 different documents

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#133]
The editor should accept a `diff` between 2 different documents.

This `diff` will then be interpreted and inline of the field a widget will be displayed to propose the change (add, remove and so on).

When a user accepts the change, the document will be modified.

For INSPIRE use case, the `diff` can be sent from the https://github.com/inspirehep/record-editor (see https://github.com/inspirehep/record-editor/issues/102)

**Comment by jmartinm** [comment]
How to see diff examples locally
=========================

```bash

mkvirtualenv json-merger
cdvirtualenv
mkdir src
cd src

# shortcuts thanks to https://github.com/github/hub
git clone inveniosoftware-contrib/json-merger
git clone inspirehep/json-merger-viewer

cd json-merger
pip install -e .

cd ../json-merger-viewer
npm install
pip install -r requirements.txt
./app_rw.py
```

Then you should see:

<img width="1676" alt="screen shot 2017-01-25 at 4 54 29 pm" src="https://cloud.githubusercontent.com/assets/580727/22300315/fd02b01a-e31e-11e6-98af-a3bf3a825f4c.png">

To have many more examples of merging (extracted from real merges in inspirehep):

1) Download https://cernbox.cern.ch/index.php/s/2sc5Oks2dsyGh8N
2) Unzip all the folders inside of `json-merger-viewer/uploads`

<img width="1653" alt="screen shot 2017-01-25 at 4 57 17 pm" src="https://cloud.githubusercontent.com/assets/580727/22300430/5ae13a76-e31f-11e6-8099-3420c5855e60.png">

The possible conflicts are documented [here](https://pythonhosted.org/json-merger/api.html#json_merger.conflict.ConflictType).

* REORDER - Example in upload 100761
* MANUAL_MERGE - Example in author_double_match_conflict
* ADD_BACK_TO_HEAD - Example in 100761 (select on top Keep Update Entities Conflict On Head Delete)
* SET_FIELD - Example in 100761
* REMOVE_FIELD (did not find an example yet)

**Comment by jmartinm** [comment]
Use cases
========

* User submits an author update and needs to be merged with the corresponding author record.
* An update for an existing arXiv paper arrives.
* A publisher version arrives and needs to be merged with the preprint.
* There is a duplicate on the database so 2 records get manually merged.  Example - https://cernbox.cern.ch/index.php/s/2sc5Oks2dsyGh8N

**Comment by jmartinm** [comment]
UI mockup (in progress)
=================

Thanks to @StellaCh 

![5432256](https://cloud.githubusercontent.com/assets/580727/22345888/d08541f2-e3f9-11e6-9696-143badcb8d82.png)

**Comment by StellaCh** [comment]
- Keep the new fields in their final position
- Do not allow editing fields that have a conflict
- The + button is used only when the whole text is replaced
- Navigate with Next and a shortcut
- The number of changes will be automatic depending on how many changes are left

**Comment by StellaCh** [comment]
As discussed, conflicts appear with glyphicon glyphicon-flash 
<img width="170" alt="screen shot 2017-07-26 at 14 06 48" src="https://user-images.githubusercontent.com/24955201/28620057-9feab428-720b-11e7-9030-82311b6f86f1.png">

<img width="494" alt="screen shot 2017-07-26 at 14 06 58" src="https://user-images.githubusercontent.com/24955201/28620059-a3061abc-720b-11e7-969a-a263d192d3ca.png">

**Comment by harunurhan** [comment]
This is resolved, for further development of a related feature or UI change, please create another issue.
