### ISSUE TITLE
Support display modes

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#146]
Since different users deal with different parts of the records on a daily basis, it is useful to have display modes like we currently have:

<img width="947" alt="screen shot 2017-01-20 at 10 26 01 am" src="https://cloud.githubusercontent.com/assets/580727/22143641/0424ab6e-defb-11e6-9850-ab00bddd4bb6.png">

They should support:

1) Configuration: name of display mode -> Fields
2) UI: show the display modes and allow to change between them (on the left panel under the navigation of fields)
3) BONUS: Make a display default based on the user that is using the editor

**Comment by harunurhan** [comment]
Closed by #209 which provided same functionality.
