### ISSUE TITLE
Configurable enable/disable sorting

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#169]
At the moment, all list fields have sorting handlers.

<img width="813" alt="screen shot 2017-01-31 at 1 05 45 pm" src="https://cloud.githubusercontent.com/assets/580727/22464220/04aad8b0-e7b6-11e6-8887-50ea00c17023.png">

In practice, only in few fields ordering is important, so we don't need to clutter the interface with all the sorting icons.

Solution
======

* Add new config to `schemaOptions` - `enableSorting` that will show the sorting icons.
* By default do not show the sorting options

**Comment by harunurhan** [comment]
This is better to be done together with #170

**Comment by zzacharo** [comment]
@harunurhan @jmartinm I had started with the #170 in some point. I made it work with html5 drag-n-drop feature.

**Comment by jmartinm** [comment]
> @harunurhan @jmartinm I had started with the #170 in some point. I made it work with html5 drag-n-drop feature.

Can you share the code and link to it from https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/170 ?

**Comment by zzacharo** [comment]
Check my sample implementation https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/170#issuecomment-288009803
