### ISSUE TITLE
Shortcut navigate left/right not working after editing value

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#174]
How to replicate
============

In a field like `keywords`, modify the field value and with focus still on the field do the shortcut `Command+left`.

The focus does not change to the field to the right/left as expected.

**Comment by zzacharo** [comment]
This is fixed on this PR https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/200. So I close it.
