### ISSUE TITLE
Move up/down does not update tabindex

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#175]
How to reproduce
=============

After moving fields up/down, tabindexes do not seem to update correctly, so tab does not work as expected:

![shortcut](https://cloud.githubusercontent.com/assets/580727/22640390/ae1d7984-ec52-11e6-8836-266cfc754c55.gif)

**Comment by zzacharo** [comment]
@jmartinm yes because the update of tabindexes are not integrated in the shortcuts PR. I will make another PR for this!

**Comment by zzacharo** [comment]
@jmartinm Or I will fix it directly to https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/165 . What do you say?

**Comment by jmartinm** [comment]
Yes, you can add an extra commit fixing this to https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/165
