### ISSUE TITLE
jsonschema validator

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#182]
Related to https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/163 and https://github.com/inspirehep/record-editor/issues/108

Errors from the jsonschema should also be taken into account. The keys to use for validation are `format`, `pattern`, `required`, `uniqueItems`.

**Comment by jmartinm** [comment]
@kaplun any other keys on the schema that should be checked on the editor?

**Comment by jmartinm** [comment]
By the way, at the moment, custom validators (that require some more logic) will be run on the server while this jsonschema validation will run on the client.

We need to make sure that we don't reinvent the wheel and implement the validation of jsonschema on the client side if there is some library that can do it for us (or we can do it on the server side)

**Comment by kaplun** [comment]
@jmartinm :+1: 
Maybe for `integers` you can also respect `minValue` and `maxValue` (needed for e.g. for years). And there are dates as well.

**Comment by kaplun** [comment]
http://json-schema.org/implementations#validator-javascript

**Comment by harunurhan** [comment]
Now we use https://github.com/epoberezkin/ajv which checks most of the things.
