### ISSUE TITLE
UI flicker on primitive field blur

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#192]
When a field is 'saved' by blur or Enter key, there is a quite annoying flicker happening.

![flicker](https://cloud.githubusercontent.com/assets/580727/22941014/273fbb46-f2e4-11e6-9037-453e74609831.gif)

**Comment by zzacharo** [comment]
I think after this PR https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/200 this is fixed because it was happening due to the whole row rerendering. With `trackByIndex` change on `trackBy` pipe this is fixed. @jmartinm @harunurhan should I close it?

**Comment by harunurhan** [comment]
@zzacharo I also don't see it but I thought it was fixed with `contenteditable` thing. So closing 👍
