### ISSUE TITLE
Add tabs

### ISSUE THREAD

**Issue by StellaCh** [inveniosoftware-contrib/ng2-json-editor#207]
As discussed with curators during the standup on 7/03/17, the idea is to have content organised in 3 tabs, as following: 
![tabs](https://cloud.githubusercontent.com/assets/24955201/23656982/460491ba-033c-11e7-9dd5-5ce0f5f3eab8.PNG)

- Under the tab Authors we have the JSON fields (with that order):
"collaborations"
"accelerator_experiments"
"authors"
"corporate_author"

- Under the tab References, we have the JSON fields:
 "references"
For references, can we extend the limit to 100 per page?

- Under the tab Literature, we have all the rest.

Also, we consider adding the title above the tabs, but we can discuss this in a later stage.

**Comment by harunurhan** [comment]
what we need to have something like below to config such a feature

```typescript
tabs: [
  {
    name: "Authors",
    properties: [
      "collaborations",
      "accelerator_experiments",
      "authors",
      "corporate_author"
    ]
  },
  {
    name: "References",
    properties: [
      "references"
    ]
  }
]
```

Or something quite similar which won't change anything for you, depending on how implementation will be, it could be like below:

```typescript
tabs: {
  Authors: [
    "collaborations",
    "accelerator_experiments",
    "authors",
    "corporate_author"
  ],
  References: [
    "references"
  ]
}
```

**Comment by jmartinm** [comment]
I like the first alternative better

**Comment by harunurhan** [comment]
@StellaCh @jmartinm 
Those tabs should share the same navigation menu (on the left) or the menu should change when you change the tab?

**Comment by jmartinm** [comment]
So you mean, if all fields should always be shown to navigate or if only the ones corresponding to the selected tab should be shown, right?

I would maybe say to just display the ones from the selected tab, but no preference.

**Comment by StellaCh** [comment]
Yes, it makes more sense to have on the right the fields that you see on the selected tab. Thanks!
