### ISSUE TITLE
Toggles for boolean values

### ISSUE THREAD

**Issue by StellaCh** [inveniosoftware-contrib/ng2-json-editor#208]
Boolean values in the schema take up many lines, whereas they could all be squeezed in 1 line. An alternative to the current display is to have all booleans in a row on the top right corner of the record editor represented by toggles.
I validated the concept with 6 successful user tests with the following screen:
<img width="678" alt="screen shot 2017-03-07 at 15 43 37" src="https://cloud.githubusercontent.com/assets/24955201/23661431/083616f4-034d-11e7-837b-d94e5298275d.png">

Look and feel of the toggles: http://www.bootstraptoggle.com/#colors
The booleans we have currently in the schema are 5. Below is their active and inactive states: 
<img width="768" alt="screen shot 2017-03-07 at 15 44 13" src="https://cloud.githubusercontent.com/assets/24955201/23661438/0d18f204-034d-11e7-9b10-fc54842ad804.png">

**Comment by harunurhan** [comment]
What we need to configure is their color, so there could be a `SchemaOptions` property like `toggleColor`, in that case you have to

```typescript
'/deleted': {
   // other things
   toggleColor: 'red'
}
```

or if you prefer outside of `schemaOptions` we can have

```typescript
toggles: [
  {
     path: '/deleted'
     color: 'red'
  }
 ...
]
```

I don't know which you'd prefer. @StellaCh  @michamos
