### ISSUE TITLE
Avoid crashing when an key in config is not in the schema

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#210]
With a config like:

```
          '/publication_info/items': {
            alwaysShow: ['journal_title', 'journal_volume', 'journal_issue', 'artid', 'cnum', 'year', 'confpaper_info']
          },
```

If, for example, the last key `confpaper_info` is not in the schema, the editor breaks with:

<img width="1678" alt="screen shot 2017-03-20 at 9 26 02 am" src="https://cloud.githubusercontent.com/assets/580727/24092559/4620e780-0d4f-11e7-91d0-a552f6566947.png">

**Comment by harunurhan** [comment]
Actually this error is a categorised one already.

In order to ignore this, the best way is remove those ones with `O(n)` check  for each field that has `alwaysShow` at the beginning in `schema-fixer.service`. But I am not sure that's worth it just to do a warning, @jmartinm

**Comment by jmartinm** [comment]
A different error that crashes the editor. With this record https://gist.github.com/jmartinm/35e9c5d383db524a1174691398b827d1 the following error occurs:

```javascript
TypeError: Cannot delete property '0' of [object String]
    at t.deleteField (https://newlabs.inspirehep.net/static/gen/record-editor.fec55705.js:415:6470)
    at https://newlabs.inspirehep.net/static/gen/record-editor.fec55705.js:415:6113
    at Array.forEach (native)
    at t.fix (https://newlabs.inspirehep.net/static/gen/record-editor.fec55705.js:415:6048)
    at https://newlabs.inspirehep.net/static/gen/record-editor.fec55705.js:415:6401
    at Array.forEach (native)
    at t.fix (https://newlabs.inspirehep.net/static/gen/record-editor.fec55705.js:415:6377)
    at https://newlabs.inspirehep.net/static/gen/record-editor.fec55705.js:415:6086
    at Array.forEach (native)
    at t.fix (https://newlabs.inspirehep.net/static/gen/record-editor.fec55705.js:415:6048)
    at https://newlabs.inspirehep.net/static/gen/record-editor.fec55705.js:415:6086
    at Array.forEach (native)
    at t.fix (https://newlabs.inspirehep.net/static/gen/record-editor.fec55705.js:415:6048)
    at https://newlabs.inspirehep.net/static/gen/record-editor.fec55705.js:415:6401
    at Array.forEach (native)
```

**Comment by harunurhan** [comment]
@jmartinm  is this not related to config? and does it happen on start?

**Comment by harunurhan** [comment]
@jmartinm  I checked and `schema` and `record` on `newlabs` don't even match. Schema expects `references/authors` to be an object array with `full_name` and `role` properties but in the record that you shared has string array.

So this is not an issue for here, although I thought we were throwing more relevant errors in those cases so I need to double check something might be broken, so that we can't categorise this one.

**Comment by jmartinm** [comment]
> @jmartinm I checked and schema and record on newlabs don't even match. Schema expects references/authors to be an object array with full_name and role properties but in the record that you shared has string array.

Yes, I expected that to be the case.

The thing for this issue was to check if we can give a better error or just skip these problems and give a warning on console.
