### ISSUE TITLE
contenteditable divs grow over other elements

### ISSUE THREAD

**Issue by harunurhan** [inveniosoftware-contrib/ng2-json-editor#211]
<img width="159" alt="screen shot 2017-03-20 at 15 40 36" src="https://cloud.githubusercontent.com/assets/4868667/24104888/a30089cc-0d83-11e7-9051-f587db66b202.png">

**Comment by harunurhan** [comment]
## Before

![screen shot 2017-03-22 at 16 30 57](https://cloud.githubusercontent.com/assets/4868667/24205848/d542cea0-0f1c-11e7-9dac-b1ef178ac637.png)

## After

![screen shot 2017-03-22 at 16 30 43](https://cloud.githubusercontent.com/assets/4868667/24205854/dabc6b7a-0f1c-11e7-81f0-5f921a1a8440.png)


### Problems

- there is a bit disturbing overflow when focusing on the next field
![screen shot 2017-03-22 at 16 31 10](https://cloud.githubusercontent.com/assets/4868667/24205864/e4af0b60-0f1c-11e7-8421-3199fc0dd736.png)

- I don't know how but if do random things, scroll might be stuck on the field even if it's not focused and it looks weird for one liners.

![screen shot 2017-03-22 at 16 31 32](https://cloud.githubusercontent.com/assets/4868667/24205984/367e2a34-0f1d-11e7-8898-af249cd41344.png)


@jmartinm  @StellaCh

**Comment by StellaCh** [comment]
The most user-friendly solution is to expand the field in another line.
However, is 'source' the only field we get this issue? The source will never be too long and we can configure it in the right length so that we never stumble upon this issue.

**Comment by harunurhan** [comment]
@StellaCh input is broken by word into a new line already, this issue happens only when there is something really long without any space, such as links. 

This can happen anywhere, actually I think it will happen with tables that have more than 5 columns. So that's why we have to fix it.

**Comment by harunurhan** [comment]
The other issue with scroll is we lose outline. 

#### blue outline when focused
![screen shot 2017-03-23 at 09 27 45](https://cloud.githubusercontent.com/assets/4868667/24238534/e462c7ee-0faa-11e7-8ed5-21e10a11487c.png) 

#### no outline when focused
![screen shot 2017-03-23 at 09 28 26](https://cloud.githubusercontent.com/assets/4868667/24238535/e4681ab4-0faa-11e7-9e0e-a4d9e21f15d5.png)
