### ISSUE TITLE
Support dates

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#224]
The editor shows an error message instead of showing the date itself:

![screenshot from 2017-03-21 20-19-34](https://cloud.githubusercontent.com/assets/587148/24166525/d3e28158-0e73-11e7-9f92-e7bb2872cd08.png)

Moved from https://github.com/inspirehep/inspire-next/issues/2086

**Comment by harunurhan** [comment]
@jmartinm to what level exactly we want to support? showing them as string or date picker like component?

**Comment by harunurhan** [comment]
for `"type": "string"` we always show them as `string` but actually in this case, https://github.com/inspirehep/inspire-schemas/issues/131 is the issue here.

So if you don't want a datepicker we can close the issue.

**Comment by jmartinm** [comment]
We can close this for now as long as we show the date as a string. Don't think a date picker is needed.
