### ISSUE TITLE
Pressing <Enter> should not write '\n' in value

### ISSUE THREAD

**Issue by michamos** [inveniosoftware-contrib/ng2-json-editor#237]
Currently, when pressing enter after inputting a string value results in an explicit carriage return (`\n`) written in the field. This should not happen.

**Comment by harunurhan** [comment]
@michamos This doesn't happen for me, but I am gonna check on firefox to reproduce.

**Comment by harunurhan** [comment]
Since we couldn't reproduce it also on firefox, I will close it for the moment.
