### ISSUE TITLE
Left menu improvements

### ISSUE THREAD

**Issue by StellaCh** [inveniosoftware-contrib/ng2-json-editor#245]
Based on our user feedback, we discussed the following improvements:

- [x] When you select or add an item on the left menu, then the field in the editor stays highlighted. The yellow highlight goes away only on blur. One field is highlighted at a time.

- [x] Boolean toggles appear in the left menu too. When selected, the page goes up and they get also highlighted.

- [x] The tree structure of the menu items hasn't proved useful, so we keep the menu items only in the first level (delete deeper levels)

- [x] Add all fields in all tabs. When selecting a field that belongs to another tab, then the correct tab gets automatically selected

- [ ] The menu items should be in alphabetical order (otherwise it's not logical for the users)

- [x] The search bar is not needed. (ctrl-F has been proven enough for searching)

**Comment by harunurhan** [comment]
@jmartinm other than deleting the code for the recursive menu, shall we have a config flag for that and make it non recursive by default?
