### ISSUE TITLE
do normalization of fields

### ISSUE THREAD

**Issue by annetteholtkamp** [inveniosoftware-contrib/ng2-json-editor#249]
The schema enforces patterns on some fields (e.g. ISBN without dashes), so if a field does not conform to the pattern an error is raised. It would by nice if the editor could do some normalization (e.g. stripping the dashes from the ISBN) so the curator doesn't have to.

**Comment by annetteholtkamp** [comment]
(@michamos wrote this on my computer)

**Comment by harunurhan** [comment]
@michamos So this is like, you have to run a function after a particular a field edited (value changed and enter is clicked or unfocused) and normalize the field?

**Comment by michamos** [comment]
:+1: for example for ISBNs you could use `asIsbn13()` from https://www.npmjs.com/package/isbn

**Comment by harunurhan** [comment]
Moved to https://github.com/inspirehep/record-editor/issues/247
