### ISSUE TITLE
What to disable exactly when a field is disabled

### ISSUE THREAD

**Issue by harunurhan** [inveniosoftware-contrib/ng2-json-editor#254]
We need to decide what to disable on the UI of a disabled field for every case such an array item, an array, an object, a string.

**Comment by harunurhan** [comment]
Handling `disabled` field is a bit messed up now, since it wasn't clear what we can and can't do with them. Surely modifying value or any subfield value of a disabled is not allowed. But it would be good If we make clear which are the below is allowed.

- adding a new item to disabled `array` type field.
- deleting items from disabled `array` type field.
- adding a new field to disabled `object` type field.
- deleting a field from disabled `object` type field.
- adding a disabled field as subfield to its parent field.
- deleting disabled subfield from its parent field.
- ordering elements in disabled `array` type field.

Although all `array` wide action could be worked around by setting the `/path/to/array/items` as disabled not `/path/to/array`, object type ones a bit unclear.

**Comment by StellaCh** [comment]
@michamos can you help with the requirements?

**Comment by StellaCh** [comment]
Discussing it with Micha, disabled fields should not be added, deleted nor reordered.
