### ISSUE TITLE
Impossible to add deleted fields that were in the record in the begining

### ISSUE THREAD

**Issue by michamos** [inveniosoftware-contrib/ng2-json-editor#270]
When opening the example record https://inveniosoftware-contrib.github.io/ng2-json-editor/ and deleting a field that is there (e.g. `preprint_date`), it is impossible to add that field later: it does not show up in the `Add field` menu on the left.

**Comment by harunurhan** [comment]
This is fixed but not yet released and we deploy it to github pages when there is a release, that's why it's still a bug there.
