### ISSUE TITLE
ajv schema validation: relax format rules

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#276]
When the schema contains `format:date` the following error is raised on the client side:

![screen shot 2017-04-26 at 10 01 33 am](https://cloud.githubusercontent.com/assets/580727/25424185/bcba09fa-2a67-11e7-9865-06e1affe0027.png)

We need a way to relax this rules (pass custom ones or disable them) since this formats are not really mandatory in JSON Schema.

For example on INSPIRE we allow dates in the formats YYYY, YYYY-MM or YYYY-MM-DD

**Comment by jmartinm** [comment]
@zzacharo please have a look when you have time.

**Comment by zzacharo** [comment]
@jmartinm  I will check how I can ignore them.

**Comment by harunurhan** [comment]
This should be done on record-editor and custom validators passed in config.
@zzacharo is this already done?

**Comment by zzacharo** [comment]
@harunurhan I think yes.
