### ISSUE TITLE
Error when disabling tabs

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#282]
When `tabsConfig` is not set, there are several errors, when the page loads:

```
vendor.bundle.js:140768 Uncaught TypeError: Cannot read property 'apply' of undefined
```

And when deleting an element such as references:

```javascript
    at ComplexListFieldComponent.webpackJsonp.778.AbstractFieldComponent.ngOnDestroy (main.bundle.js:2780)
```

**Comment by harunurhan** [comment]
first one does not happen to me, and the second one is also happens with tabs it's from `error-panel` PR similar thing was happening with `primitive-list` and @zzacharo fixed, so he can have a look at this one as well.

**Comment by harunurhan** [comment]
This issue could be fixed by only putting `if` to check `undefined` but I am trying to understand why we need it :)
