### ISSUE TITLE
add search field in authors tab

### ISSUE THREAD

**Issue by StellaCh** [inveniosoftware-contrib/ng2-json-editor#290]
There's often the need to search inside authors if there’re results with several pages.
At the top of the authors tab, add a search field similar to the search field in the references tab:

![search field](https://cloud.githubusercontent.com/assets/24955201/25938156/9a9f5dfc-362e-11e7-8346-b19e67ea2537.PNG)

**Comment by harunurhan** [comment]
This is a config, since I created this https://github.com/inspirehep/record-editor/issues/142
