### ISSUE TITLE
Enable admin mode bug

### ISSUE THREAD

**Issue by StellaCh** [inveniosoftware-contrib/ng2-json-editor#291]
1. When clicking on 'Enable admin mode', fields like dois are supposed to be editable, but nothing changes: eg. in https://qa.inspirehep.net/editor/literature/1472986 

2. In some records, 'Send feedback' hides the 'Enable admin mode' checkbox and there's no way to click it. Eg. https://qa.inspirehep.net/editor/literature/1497201 
![admin](https://cloud.githubusercontent.com/assets/24955201/25939460/3f358afe-3633-11e7-9f8c-c3eb243291ff.PNG)

**Comment by harunurhan** [comment]
first one is already here: #243 but the second one I am not sure if we should fix it here, what do you think @jmartinm ?

**Comment by jmartinm** [comment]
>  but the second one I am not sure if we should fix it here, what do you think @jmartinm ?

The second one I will have a look and fix it on the INSPIRE template side.

**Comment by jmartinm** [comment]
> The second one I will have a look and fix it on the INSPIRE template side.

It is now fixed.

**Comment by harunurhan** [comment]
Resolved
