### ISSUE TITLE
add margin at the end of the page

### ISSUE THREAD

**Issue by StellaCh** [inveniosoftware-contrib/ng2-json-editor#292]
> I want to add an isbn, but I don't see it in the list

When the cursor is in the 'Add field' area, the message javascript:void(0) hides the last line, where isbns option is supposed to be.

![js1](https://cloud.githubusercontent.com/assets/24955201/25940562/cea5fec8-3636-11e7-8c81-390afb5d1a54.PNG)

However, when we are not in full screen, there's no problem, the 'isbns' option appears correctly:
![js2](https://cloud.githubusercontent.com/assets/24955201/25940555/caacc07c-3636-11e7-8610-d101416f9d2c.PNG)

**Comment by harunurhan** [comment]
@StellaCh 

This is how it looks when you mouse hover on another element, sure it doesn't display the last.

![screen shot 2017-05-16 at 11 16 44](https://cloud.githubusercontent.com/assets/4868667/26098760/0f1377c4-3a29-11e7-8d85-9a9fbd530a49.png)

However chrome (also firefox) already handles when you hover on the last one by hiding the url thing.

![screen shot 2017-05-16 at 11 16 51](https://cloud.githubusercontent.com/assets/4868667/26098811/3de1fc7e-3a29-11e7-8d76-a00f59f35adb.png)

Do you think that we still need a margin?

**Comment by StellaCh** [comment]
Yes, we need a margin. During the user tests, several users failed to see the isbn option and thought that something's wrong with the editor. In most cases, the way to search the isbn will be by hovering over other elements, so  often they won't be able to see the 'isbn' option.
