### ISSUE TITLE
LaTeX in titles

### ISSUE THREAD

**Issue by StellaCh** [inveniosoftware-contrib/ng2-json-editor#294]
> I would like to see quickly if the title is in the correct LaTeX form without having to click on Save to preview the page

### Ideal solution: 
On focus: The title shows the editable version:
![title](https://cloud.githubusercontent.com/assets/24955201/25943028/d796f336-363e-11e7-8be9-8deeac395b4e.PNG)

Out of focus: The latex version is shown: 
![title](https://cloud.githubusercontent.com/assets/24955201/25943466/39458a10-3640-11e7-8eb4-d0e1f8cddba4.PNG)

If, during the investigation of the solution, you estimate that the implementation will take more time than the deadline of the milestone:

### Intermediate solution: 
Add a tooltip with the LateX version of the title, which appears on mouse over.

**Comment by harunurhan** [comment]
https://github.com/Khan/KaTeX could be used.

**Comment by harunurhan** [comment]
Fixed
