### ISSUE TITLE
Show Preview button isn't completely visible

### ISSUE THREAD

**Issue by harunurhan** [inveniosoftware-contrib/ng2-json-editor#296]
<img width="318" alt="screen shot 2017-05-16 at 15 58 49" src="https://cloud.githubusercontent.com/assets/4868667/26109780/8ccc8ec2-3a50-11e7-80d7-0b67edf25a63.png">

**Comment by jmartinm** [comment]
For me this seems correctly visible

**Comment by harunurhan** [comment]
this happens in smaller screens
