### ISSUE TITLE
Error messages bugs

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#315]
1) If you add to a reference field a `doi` and then delete the `doi`, a new error is added to the error panel even though there is no value.

2) Errors are not shown when tabbing outside of a field. If I am inside of the `doi` field, type a wrong one and tab, the error is not shown.

**Comment by harunurhan** [comment]
@zzacharo maybe you could take this one? and I'll take over #276

**Comment by jmartinm** [comment]
Fixed.
