### ISSUE TITLE
Add sticky pagination component for long list navigator

### ISSUE THREAD

**Issue by harunurhan** [inveniosoftware-contrib/ng2-json-editor#334]
Reference: https://github.com/inspirehep/record-editor/issues/156

**Comment by harunurhan** [comment]
Nice option to check out for this task: https://github.com/makseo/ng2-sticky

**Comment by jmartinm** [comment]
> Nice option to check out for this task: https://github.com/makseo/ng2-sticky

Looks nice. I did not manage to make the demo run locally though.
