### ISSUE TITLE
Return clean json from json-editor

### ISSUE THREAD

**Issue by harunurhan** [inveniosoftware-contrib/ng2-json-editor#37]
Currently we apply some fixes on the record to make UI (usually `table-list`) to look cool. But this changes structure of the record (flattening) and inserts empty values.

To solve this, we'll remove flattening and instead of inserting empty values when a key undefined, just use a pipe or some function like `selfOrEmptyValueIfUndefined` on the template so that we could fix the UI without changing the record. So we won't need to run a cleanup function

**Comment by harunurhan** [comment]
I realized that we also do some manipulations for `x_editor_hidden` and `x_editor_always_show`, so do we have to deal with them unfortunately.

My idea for `x_editor_always_show` is that we won't need to force it on input record but only when a new value added. And for `x_editor_hidden` we can implement functionality that passes those fields in `mapToSortedIterable` pipe or in a new pipe.

what do you think @jmartinm ?

**Comment by jmartinm** [comment]
> My idea for x_editor_always_show is that we won't need to force it on input record but only when a new value added

This one I am not sure. The idea with `x_editor_always_show` is that when you open the record those fields are shown in the interface to guide what fields are recommended to be filled.

So it is not only useful with new value added but also upon opening the record.

**Comment by jmartinm** [comment]
Done in https://github.com/inveniosoftware-contrib/ng2-json-editor/pull/54.
