### ISSUE TITLE
Add dynamic shortcut cheatsheet

### ISSUE THREAD

**Issue by harunurhan** [inveniosoftware-contrib/ng2-json-editor#384]

**Comment by harunurhan** [comment]
This will required put the comments in https://github.com/inveniosoftware-contrib/ng2-json-editor/blob/master/src/shared/interfaces/custom-shortcuts.ts to a variable of each entry in `shorcuts` in https://github.com/inveniosoftware-contrib/ng2-json-editor/blob/master/src/shared/services/shortcut.service.ts

**Comment by harunurhan** [comment]
The link is to shortcut documentation: https://inveniosoftware-contrib.github.io/ng2-json-editor/docs/interfaces/_interfaces_custom_shortcuts_.customshortcuts.html

**Comment by StellaCh** [comment]
The shortcut documentation is not clear for non developers, it should definitely be presented in a more user-friendly way. It should be similar to https://inspirehep.net/help/admin/bibedit-admin-guide#2

We need a help page when clicking on the question circle on the top right of the editor:

<img width="271" alt="screen shot 2017-09-05 at 13 53 07" src="https://user-images.githubusercontent.com/24955201/30060106-4060004c-9242-11e7-8279-2a35e7f4cd1b.png">

The page should also open with a shortcut.
Clicking on the question circle opens a modal that contains:

- schema documentation and
- shortcut documentation

**Comment by harunurhan** [comment]
@jmartinm if we agree that we don't need dynamic cheatsheet thing, I can close this open another issue on `record-editor` for adding a link to static help page?

**Comment by jmartinm** [comment]
Yes, it's better to add something custom on `record-editor` - instead of opening a new static page, as Stella suggests in the record editor the help button can open a modal with the shortcuts (and a link to the schema documentation)
