### ISSUE TITLE
Configurable keyboard shortcut support

### ISSUE THREAD

**Issue by harunurhan** [inveniosoftware-contrib/ng2-json-editor#4]
@harunurhan commented on [Wed Jul 20 2016](https://github.com/inspirehep/record-editor/issues/19)

The editor should have useful keyboard shortcuts for record navigation and other functionalities.

Also It should be possible to overwrite default shortcuts for available actions via a configuration file (json or yaml).

This kind of library might be useful https://github.com/brtnshrdr/angular2-hotkeys
### List of shortcut actions
- All in https://inspirehep.net/help/admin/bibedit-admin-guide#2  (from #18)

**TO BE ADDED MORE**

---

@jmartinm commented on [Thu Jul 28 2016](https://github.com/inspirehep/record-editor/issues/19#issuecomment-235850602)

@harunurhan can you merge with https://github.com/inspirehep/record-editor/issues/18

---

@harunurhan commented on [Mon Aug 29 2016](https://github.com/inspirehep/record-editor/issues/19#issuecomment-243146596)

I was doing some initial work this issue and using https://github.com/brtnshrdr/angular2-hotkeys which is based on https://github.com/ccampbell/mousetrap, and had annoying performance drop.

You can have a look two gifs
### Before angular2-hotkeys

![without-hotkeys](https://cloud.githubusercontent.com/assets/4868667/18055368/cef0790a-6e07-11e6-9e6d-b6a70eaeb371.gif)
### After angular2-hotkeys

![with-hotkeys](https://cloud.githubusercontent.com/assets/4868667/18055456/34760fd8-6e08-11e6-8c7a-0b4c7ce71763.gif)

I haven't investigated much about what is causing this, @eamonnmag maybe you have an idea since (AFAIK) you have used a the `angular1.x` version of this before.

---

@kaplun commented on [Mon Aug 29 2016](https://github.com/inspirehep/record-editor/issues/19#issuecomment-243169732)

Woah that is really a performance impact. I guess the fan is also twisting...

**Comment by zzacharo** [comment]
@jmartinm @harunurhan i saw performance issue again with angular2-hotkeys when i used them as directives. Additionally, we have this build issue. Is it worth to implement this in our way? I mean i can copy any of the code that we need from this https://github.com/brtnshrdr/angular2-hotkeys and also change the build system. We can make more specific to our needs or create a new better version of this :P . What do you propose?

**Comment by jmartinm** [comment]
That library seems to be a small wrapper over https://craig.is/killing/mice

It does not have that much code so you could check if you can find where the performance issue is.

**Comment by zzacharo** [comment]
@jmartinm yes angular2-hotkeys is based on this library. I was thinking about create a module based on this library. But i don't know if the problem is on this mousetrap module or on the implementation of the angular2-hotkeys.

**Comment by jmartinm** [comment]
Sure, feel free to experiment with that library to see if you can find what might be the cause of the slow down.
