### ISSUE TITLE
display values for enum (searchable-dropdown)

### ISSUE THREAD

**Issue by harunurhan** [inveniosoftware-contrib/ng2-json-editor#408]
We should have config to support display values for enum fields.

**Comment by harunurhan** [comment]
@StellaCh would it make sense to see and filter the user friendly values on the dropdown but when you select the original value appears?

**Comment by StellaCh** [comment]
Not really, because the issue still remains if a user opens the editor and sees the original value on the field without knowing what it means.

**Comment by harunurhan** [comment]
I see, only problem with this it can create some inconsistency if these values displayed elsewhere in its original form. But I don't think this is the case probably.
