### ISSUE TITLE
Compact view: scrollbar

### ISSUE THREAD

**Issue by Glignos** [inveniosoftware-contrib/ng2-json-editor#423]
The scrollbar in compact view should be inside the listed options.
There is a remaining blue border on the left.

**Comment by harunurhan** [comment]
@Glignos can you put a screenshot and explain what's wrong because I forgot 😟

**Comment by Glignos** [comment]
To fix some styling issues for the compact version it is needed to remove:
padding:0px; from middle.main-container
border-left: 1px solid from main-container
Also the scrollbar for the fields dropdown appears outside of the editor
