### ISSUE TITLE
make the sidebar collapsable

### ISSUE THREAD

**Issue by drjova** [inveniosoftware-contrib/ng2-json-editor#455]
The sidebar takes a lot of space, the idea is to make it collapsable (by default collapsed).

- [ ] Update the ``js-editor.component`` to include the sidebar's state (``collapsed ? true : false``)
  - [ ] Fix the bootstrap grid to take advantage of the extra space when the sidebar is collapsed
  - [ ] Update the ``json-editor.component.html`` to render the different states (attached mockup)
- [ ] Pass the sidebar's state to the ``bottom-console-badges``
  - [ ] Update the ``bottom-console-badges`` to render the buttons depending on the state
- [ ] Pass the sidebar's state to the ``add-field-dropdown``
  - [ ] Update the ``add-field-dropdown`` to render the dropdown next to the sidebar when sidebar is collapsed (floating)

Sidebar mockup:

![record-editor](https://user-images.githubusercontent.com/4287772/35052272-7852bc0a-fba7-11e7-80c4-80883d9d74e8.png)

**Comment by harunurhan** [comment]
@drjova shall we close this?

**Comment by drjova** [comment]
@harunurhan yep is already merged :)
