### ISSUE TITLE
pdf preview - copy/paste content

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#50]
The PDF previewer does not seem to allow at the moment to copy paste content. That would mean that a cataloger would have to manually type the content into the editor.

Check if it is possible with the current previewer to render the PDF in a way that allows copy/paste. At the moment the preview seems to be an image representation of the pdf.

**Comment by harunurhan** [comment]
Actually it is possible but unfortunately `pdf.js` is not very good at this and requires higher quality pdfs  to allow selecting chars.
