### ISSUE TITLE
update to latest angular-cli

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#69]
Related to https://github.com/inspirehep/record-editor/issues/89

* [ ] Update to latest `angular-cli`

**Comment by harunurhan** [comment]
Blocked by https://github.com/angular/angular-cli/issues/3077

**Comment by jmartinm** [comment]
Can be solved with this workaround https://github.com/valor-software/ng2-bootstrap/commit/8eea379

**Comment by harunurhan** [comment]
Resolved
