### ISSUE TITLE
Add component for raw type fields

### ISSUE THREAD

**Issue by harunurhan** [inveniosoftware-contrib/ng2-json-editor#9]
@harunurhan commented on [Thu Aug 11 2016](https://github.com/inspirehep/record-editor/issues/55)

If schema of a field is empty object `{ }` then it is considered as `raw` field. We should have a component to render this case.

How should this look like?

NOTE: This should be implemented, after #54 is merged, (see: https://github.com/inspirehep/record-editor/pull/54/files#diff-2df51a345cb04e714981baf10212beb8R50)

**Comment by jmartinm** [comment]
I don't remember what is the status of this. Do we have raw field examples at the moment? Is it related to https://github.com/inspirehep/inspire-schemas/pull/38 ?

**Comment by harunurhan** [comment]
I think fields in records such as `_scheme`, `_term` and `_degree_type` should be added to schema as a `raw`.

**Comment by jmartinm** [comment]
> I think fields in records such as _scheme, _term and _degree_type should be added to schema as a raw.

To which schema? In here https://github.com/inspirehep/inspire-schemas ?

By raw you mean adding `{}` as schema?

**Comment by harunurhan** [comment]
For instance, `_term` and `_scheme` which hold respectively raw versions of `term` and `scheme`. They should go to `elements/field.json`. It's not related to this issue but we also talked about changing prefix to `raw_` instead of `_`.

And yes I meant `{}`.

**Comment by harunurhan** [comment]
https://github.com/Microsoft/monaco-editor could be really useful for this feature if it has the cool features for `json` as `vscode` since it's the base library used in `vscode`

**Comment by harunurhan** [comment]
Will be reopened if needed
