### ISSUE TITLE
Field raw editing

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware-contrib/ng2-json-editor#93]
Can be connected to https://github.com/inveniosoftware-contrib/ng2-json-editor/issues/9.

For complex cases where one wants to perform, for example, a search/replace operation in one field, it is helpful to see the raw field (in JSON) and be able to extract it into a text editor and paste back again.

Proposal
======

* [ ] Add button close to the top level labels such as `abstracts`, `authors` that when clicked will open a modal with the raw JSON for that field.
* [ ] Can be helpful to have a global `Edit Raw` button, that will allow to edit the whole record. This should filter out the fields that are non-editable such as `control_number`.
* [ ] When the JSON is modified, it will have to be checked to make sure it is still valid JSON with no syntax errors.

**Comment by harunurhan** [comment]
Shouldn't #9 and this one have more priority? @jmartinm

**Comment by harunurhan** [comment]
Will be reopened if needed
