### ISSUE TITLE
Docs format

### ISSUE THREAD

**Issue by harunurhan** [inveniosoftware-contrib/ng2-json-editor#96]
I think before it gets too big, we should find a good format for documentation that is compatible with one of the doc page generators.

@jmartinm ?

**Comment by jmartinm** [comment]
If it is for the code, after some google searching I have seen this one http://typedoc.org/

Can you have a look and propose some alternatives?

**Comment by harunurhan** [comment]
For the code, existing function comments are already good. But I meant for configs that are in `README.md`

**Comment by jmartinm** [comment]
OK, I think the current one is quite organized so far. A bigger one with table of contents is this one https://github.com/angular/angular-cli. Any suggestions on what to improve?

**Comment by jmartinm** [comment]
Now that I look at this again, so what are the doc page generators?

**Comment by harunurhan** [comment]
Fixed with typedoc
